import type {AssistantResult, Speaker} from '../types';
const API_BASE = (import.meta.env.VITE_API_BASE_URL || 'http://127.0.0.1:8000/api/v1').replace(/\/$/, '');
async function request<T>(path: string, init?: RequestInit): Promise<T> { const response = await fetch(`${API_BASE}${path}`, init); if (!response.ok) throw new Error((await response.text()) || `API request failed (${response.status})`); return response.json() as Promise<T>; }
type BackendSpeaker = {candidate_user_id?: string; similarity?: number; identified?: boolean; verified?: boolean; verification?: {verified?: boolean}};
type BackendProcess = {transcript?: string; intent?: string; speaker?: BackendSpeaker; response?: string; response_text?: string; error?: string; success?: boolean};
const usernameFromId=(value:string)=>value.replace(/^user_/,'');
export async function processAudio(audio: Blob): Promise<AssistantResult> { const body = new FormData(); body.append('audio', audio, 'command.wav'); const raw = await request<BackendProcess>('/process', {method:'POST', body}); const speaker = raw.speaker?.identified && raw.speaker.candidate_user_id ? {id:raw.speaker.candidate_user_id,name:usernameFromId(raw.speaker.candidate_user_id),confidence:raw.speaker.similarity ?? 0} : undefined; const securityLevel = raw.intent === 'VIEW_PRIVATE_NOTE' ? 'verified' : speaker ? 'personalized' : 'public'; return {transcript:raw.transcript || '',securityLevel,speaker,response:raw.response ?? raw.response_text,error:raw.error,verified:raw.speaker?.verification?.verified ?? raw.speaker?.verified}; }
export async function getSpeakers(): Promise<Speaker[]> { const rows = await request<Array<Record<string, unknown>>>('/users'); return rows.map(row => {const id=String(row.user_id ?? row.id);return {id,name:usernameFromId(id),language:'Tiếng Việt',samples:Number(row.sample_count ?? row.samples ?? 5),status:'active',createdAt:String(row.created_at ?? '')}}); }
export async function deleteSpeaker(id: string): Promise<void> { await request(`/users/${encodeURIComponent(id)}`, {method:'DELETE'}); }
export async function enrollSpeaker(input:{name:string;username:string;samples:Blob[]}):Promise<unknown>{const body=new FormData();body.append('username',input.username);body.append('user_id',`user_${input.username.replace(/^user_/,'')}`);body.append('name',input.name);input.samples.forEach((sample,index)=>body.append('audio_files',sample,`sample-${index+1}.wav`));const result=await request<{success?:boolean;error?:string}>('/enroll',{method:'POST',body});if(result.success===false)throw new Error(result.error||'Backend rejected enrollment');return result;}
