import type {AssistantResult, EnrollmentResult, Speaker, SystemCommand} from '../types';
const API_BASE = (import.meta.env.VITE_API_BASE_URL || 'http://127.0.0.1:8000/api/v1').replace(/\/$/, '');
async function request<T>(path: string, init?: RequestInit): Promise<T> { const response = await fetch(`${API_BASE}${path}`, init); if (!response.ok) throw new Error((await response.text()) || `API request failed (${response.status})`); return response.json() as Promise<T>; }
async function requestBlob(path:string,init?:RequestInit):Promise<Blob>{const response=await fetch(`${API_BASE}${path}`,init);if(!response.ok)throw new Error((await response.text())||`API request failed (${response.status})`);return response.blob();}
type BackendSpeaker = {candidate_user_id?: string; similarity?: number; identified?: boolean; verified?: boolean; secret_phrase_transcript?: string; verification?: {verified?: boolean}};
type BackendProcess = {transcript?: string; normalized_transcript?: string; command_text?: string; asr_postprocessed?: boolean; intent?: string; speaker?: BackendSpeaker; response?: string; response_text?: string; error?: string; success?: boolean};
const usernameFromId=(value:string)=>value.replace(/^user_/,'');
const audioExtension=(audio:Blob)=>audio.type.toLowerCase().includes('flac')?'flac':'wav';
export const ENROLLMENT_PROMPTS = ['Bây giờ là mấy giờ rồi?','Cho tôi xem lịch học ngày mai.','Thêm lịch học thống kê lúc tám giờ sáng.','Mở ghi chú riêng tư gần nhất của tôi.','Hôm nay tôi cần kiểm tra lịch học và chuẩn bị bài thuyết trình.'] as const;
export const SYSTEM_COMMANDS: SystemCommand[] = [{intent:'GET_TIME',phrase:'Bây giờ là mấy giờ rồi?',requires_secret:false},{intent:'VIEW_SCHEDULE',phrase:'Cho tôi xem lịch hôm nay.',requires_secret:false},{intent:'VIEW_SCHEDULE',phrase:'Cho tôi xem lịch ngày mai.',requires_secret:false},{intent:'ADD_SCHEDULE',phrase:'Thêm lịch <tiêu đề> vào <ngày> lúc <giờ>.',requires_secret:false},{intent:'ADD_PRIVATE_NOTE',phrase:'Thêm ghi chú riêng tư <nội dung>.',requires_secret:true},{intent:'VIEW_PRIVATE_NOTE',phrase:'Mở ghi chú riêng tư gần nhất của tôi.',requires_secret:true}];
export async function getCommands(): Promise<SystemCommand[]> { try { return await request<SystemCommand[]>('/commands'); } catch { return SYSTEM_COMMANDS; } }
export async function synthesizeSpeech(text:string):Promise<Blob>{return requestBlob('/tts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text})});}
export async function processAudio(audio: Blob, secretAudio?: Blob): Promise<AssistantResult> { const body = new FormData(); body.append('audio', audio, `command.${audioExtension(audio)}`); if(secretAudio)body.append('secret_audio',secretAudio,`secret.${audioExtension(secretAudio)}`); const raw = await request<BackendProcess>('/process', {method:'POST', body}); const speaker = raw.speaker?.identified && raw.speaker.candidate_user_id ? {id:raw.speaker.candidate_user_id,name:usernameFromId(raw.speaker.candidate_user_id),confidence:raw.speaker.similarity ?? 0} : undefined; const protectedIntent = raw.intent === 'VIEW_PRIVATE_NOTE' || raw.intent === 'ADD_PRIVATE_NOTE'; const securityLevel = protectedIntent ? 'verified' : speaker ? 'personalized' : 'public'; return {transcript:raw.transcript || '',commandText:raw.command_text || raw.normalized_transcript || '',asrPostprocessed:raw.asr_postprocessed,intent:raw.intent,securityLevel,speaker,response:raw.response ?? raw.response_text,error:raw.error,verified:raw.speaker?.verification?.verified ?? raw.speaker?.verified,secretPhraseTranscript:raw.speaker?.secret_phrase_transcript}; }
export async function getSpeakers(): Promise<Speaker[]> { const rows = await request<Array<Record<string, unknown>>>('/users'); return rows.map(row => {const id=String(row.user_id ?? row.id);return {id,name:usernameFromId(id),language:'Tiếng Việt',samples:Number(row.sample_count ?? row.samples ?? 5),status:'active',createdAt:String(row.created_at ?? '')}}); }
export async function deleteSpeaker(id: string): Promise<void> { await request(`/users/${encodeURIComponent(id)}`, {method:'DELETE'}); }
export async function enrollSpeaker(input:{name:string;username:string;secretPhrase:string;secretSample:Blob;samples:Blob[]}):Promise<EnrollmentResult>{const body=new FormData();body.append('username',input.username);body.append('user_id',`user_${input.username.replace(/^user_/,'')}`);body.append('name',input.name);body.append('secret_phrase',input.secretPhrase);body.append('secret_phrase_transcript',input.secretPhrase);body.append('secret_audio',input.secretSample,`secret.${audioExtension(input.secretSample)}`);ENROLLMENT_PROMPTS.forEach(prompt=>body.append('enrollment_prompts',prompt));input.samples.forEach((sample,index)=>body.append('audio_files',sample,`sample-${index+1}.${audioExtension(sample)}`));return request<EnrollmentResult>('/enroll',{method:'POST',body});}
