"""Rebuild the Kaggle ECAPA notebook for all three speaker-task protocols."""

from __future__ import annotations

import json
from pathlib import Path
from textwrap import dedent


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "notebooks" / "finetune-ecapa-for-vietnamese-speaker-indentificat.ipynb"
EVALUATION_MODULE = ROOT / "src" / "speaker" / "evaluation.py"
CHECKPOINT_MODULE = ROOT / "src" / "speaker" / "checkpointing.py"


def markdown(source: str) -> dict:
    return {
        "cell_type": "markdown",
        "metadata": {},
        "source": dedent(source).strip() + "\n",
    }


def code(source: str) -> dict:
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": dedent(source).strip() + "\n",
    }


def embedded_evaluation() -> str:
    """Embed tested evaluation source so Kaggle needs no external script."""

    source = EVALUATION_MODULE.read_text(encoding="utf-8")
    return source.replace("from __future__ import annotations\n\n", "")


def embedded_checkpointing() -> str:
    source = CHECKPOINT_MODULE.read_text(encoding="utf-8")
    return source.replace("from __future__ import annotations\n\n", "")


CELLS = [
    markdown(
        """
        # Fine-tune ECAPA-TDNN on compact VoxVietnam

        Protocol:

        - Train AAM-Softmax on the closed-set classifier-train partition.
        - Compare "frozen ECAPA-TDNN" baseline after checkpoint selection.
        - Validation and test speakers are unseen and pairwise disjoint.
        - Select checkpoint and cosine threshold only from validation EER/minDCF.
        - After restoring one best checkpoint, cache every audio embedding once.
        - Evaluate closed-set LinearSVC, claimed-centroid verification, and
          gallery-centroid open-set identification with validation-only selection.

        Attach the private Kaggle dataset generated by
        `prepare-voxvietnam-on-kaggle.ipynb`. Do not publish derived audio unless
        VoxVietnam gated-access terms permit redistribution.
        """
    ),
    markdown("## 1. Install and imports"),
    code(
        """
        !pip install -q speechbrain soundfile psutil seaborn
        """
    ),
    code(
        """
        import gc
        import json
        import os
        from contextlib import nullcontext
        from pathlib import Path

        import numpy as np
        import pandas as pd
        import psutil
        import soundfile as sf
        import torch
        import torch.nn as nn
        import torch.nn.functional as F
        import torchaudio

        from sklearn.metrics import f1_score, roc_curve
        from torch.utils.data import DataLoader, Dataset
        from tqdm.auto import tqdm

        from speechbrain.inference.classifiers import EncoderClassifier
        from speechbrain.lobes.models.ECAPA_TDNN import Classifier
        from speechbrain.nnet.losses import AdditiveAngularMargin, LogSoftmaxWrapper

        os.environ.setdefault("PYTORCH_CUDA_ALLOC_CONF", "expandable_segments:True")
        """
    ),
    markdown(
        """
        ## 2. Configuration — edit only this cell

        All dataset, audio, hardware, batching, fine-tuning, and artifact
        settings live here. Later cells consume these values without redeclaring
        them. Safe default targets one T4 even when Kaggle exposes T4 x2.
        """
    ),
    code(
        """
        # Reproducibility and dataset discovery
        SEED = 42
        EXPECTED_DATASET = "voxvietnam_ecapa_three_task_v1"
        LABEL_COL = "normalized_speaker_id"

        # Audio and DataLoader
        TARGET_SAMPLE_RATE = 16_000
        SEGMENT_SECONDS = 3
        SEGMENT_SAMPLES = SEGMENT_SECONDS * TARGET_SAMPLE_RATE
        NUM_WORKERS = 0

        # Hardware and memory-safe batching for one 15 GiB T4
        AVAILABLE_GPU_COUNT = torch.cuda.device_count()
        GPU_COUNT = min(1, AVAILABLE_GPU_COUNT)
        DEVICE = torch.device("cuda:0" if GPU_COUNT else "cpu")
        USE_AMP = DEVICE.type == "cuda"
        PER_GPU_BATCH = 2
        BATCH_SIZE = PER_GPU_BATCH * max(GPU_COUNT, 1)
        TARGET_EFFECTIVE_BATCH = 32
        GRAD_ACCUM = TARGET_EFFECTIVE_BATCH // BATCH_SIZE
        assert TARGET_EFFECTIVE_BATCH % BATCH_SIZE == 0

        # Fine-tuning
        ENCODER_LEARNING_RATE = 1e-5
        CLASSIFIER_LEARNING_RATE = 1e-3
        WEIGHT_DECAY = 2e-6
        MAX_EPOCHS = 30
        WARMUP_EPOCHS = 2
        EARLY_STOPPING_PATIENCE = 3

        # Outputs
        WORKING_DIR = Path("/kaggle/working")
        CHECKPOINT_EVAL_INTERVAL = 2
        MAX_ROLLING_CHECKPOINTS = 5
        CHECKPOINT_DIR = WORKING_DIR / "checkpoints"
        BEST_CLOSED_PATH = CHECKPOINT_DIR / "best_closed.pt"
        BEST_VERIFICATION_PATH = CHECKPOINT_DIR / "best_verification.pt"
        BEST_OPEN_PATH = CHECKPOINT_DIR / "best_open.pt"
        BEST_BALANCED_PATH = CHECKPOINT_DIR / "best_balanced.pt"
        LATEST_PATH = CHECKPOINT_DIR / "latest.pt"
        MAX_CLOSED_F1_DROP = 0.005
        TRAINING_CONFIG_PATH = WORKING_DIR / "ecapa_training_config.json"
        TRAINING_HISTORY_PATH = WORKING_DIR / "ecapa_training_history.csv"
        FROZEN_EVALUATION_DIR = WORKING_DIR / "evaluation/frozen"
        FINETUNED_EVALUATION_DIR = WORKING_DIR / "evaluation/finetuned"
        SUMMARY_PATH = WORKING_DIR / "three_task_summary.csv"

        np.random.seed(SEED)
        torch.manual_seed(SEED)
        if torch.cuda.is_available():
            torch.cuda.manual_seed_all(SEED)

        print({
            "device": str(DEVICE),
            "visible_gpu_count": AVAILABLE_GPU_COUNT,
            "used_gpu_count": GPU_COUNT,
            "batch_size": BATCH_SIZE,
            "gradient_accumulation": GRAD_ACCUM,
            "effective_batch": BATCH_SIZE * GRAD_ACCUM,
        })
        """
    ),
    markdown("## 3. Locate and validate VoxVietnam dataset"),
    code(
        """
        def find_dataset_root():
            search_roots = [Path("/kaggle/input"), Path("/kaggle/working")]
            matches = []
            for search_root in search_roots:
                if not search_root.exists():
                    continue
                for manifest_path in search_root.rglob("manifest.json"):
                    try:
                        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
                    except (OSError, json.JSONDecodeError):
                        continue
                    if manifest.get("dataset") == EXPECTED_DATASET:
                        matches.append((manifest_path.parent, manifest))
            if not matches:
                raise FileNotFoundError(
                    "Attach VoxVietnam Kaggle output containing manifest.json with "
                    f"dataset={EXPECTED_DATASET!r}."
                )
            if len(matches) > 1:
                print("Multiple matching datasets found; using:", matches[0][0])
            return matches[0]


        DATASET_ROOT, DATASET_MANIFEST = find_dataset_root()
        train_metadata = pd.read_csv(DATASET_ROOT / "train/metadata.csv")
        valid_df = pd.read_csv(DATASET_ROOT / "validation/metadata.csv")
        test_df = pd.read_csv(DATASET_ROOT / "test/metadata.csv")
        closed_train_protocol = pd.read_csv(DATASET_ROOT / "protocols/closed_set/classifier_train.csv")
        closed_valid_protocol = pd.read_csv(DATASET_ROOT / "protocols/closed_set/validation_queries.csv")
        closed_test_protocol = pd.read_csv(DATASET_ROOT / "protocols/closed_set/test_queries.csv")
        valid_enrollment_protocol = pd.read_csv(DATASET_ROOT / "protocols/verification/validation_enrollment.csv")
        valid_trials = pd.read_csv(DATASET_ROOT / "protocols/verification/validation_trials.csv")
        test_enrollment_protocol = pd.read_csv(DATASET_ROOT / "protocols/verification/test_enrollment.csv")
        test_trials = pd.read_csv(DATASET_ROOT / "protocols/verification/test_trials.csv")
        open_valid_gallery = pd.read_csv(DATASET_ROOT / "protocols/open_set/validation_gallery.csv")
        open_valid_queries = pd.read_csv(DATASET_ROOT / "protocols/open_set/validation_queries.csv")
        open_test_gallery = pd.read_csv(DATASET_ROOT / "protocols/open_set/test_gallery.csv")
        open_test_queries = pd.read_csv(DATASET_ROOT / "protocols/open_set/test_queries.csv")

        all_metadata = pd.concat([train_metadata, valid_df, test_df], ignore_index=True)
        metadata_lookup = all_metadata.set_index("audio_path", drop=False)


        def attach_metadata(protocol, path_column="audio_path"):
            paths = protocol[path_column].astype(str)
            missing = sorted(set(paths) - set(metadata_lookup.index))
            assert not missing, f"Protocol paths absent from metadata: {missing[:3]}"
            return metadata_lookup.loc[paths].reset_index(drop=True)


        train_df = attach_metadata(closed_train_protocol)
        closed_valid_df = attach_metadata(closed_valid_protocol)
        closed_test_df = attach_metadata(closed_test_protocol)
        evaluation_df = all_metadata.drop_duplicates("audio_path").reset_index(drop=True)
        THREE_TASK_PROTOCOLS = {
            "closed_train": closed_train_protocol,
            "closed_validation": closed_valid_protocol,
            "closed_test": closed_test_protocol,
            "verification_validation_enrollment": valid_enrollment_protocol,
            "verification_validation_trials": valid_trials,
            "verification_test_enrollment": test_enrollment_protocol,
            "verification_test_trials": test_trials,
            "open_validation_gallery": open_valid_gallery,
            "open_validation_queries": open_valid_queries,
            "open_test_gallery": open_test_gallery,
            "open_test_queries": open_test_queries,
        }

        print("Dataset root:", DATASET_ROOT)
        print(json.dumps(DATASET_MANIFEST["splits"], indent=2))
        """
    ),
    code(
        """
        REQUIRED_METADATA = {
            "audio_id", "audio_path", "speaker_id", LABEL_COL,
            "role", "sample_rate", "checksum",
        }
        REQUIRED_TRIALS = {
            "trial_id", "enrollment_speaker_id", "query_audio_path",
            "query_speaker_id", "label",
        }

        for split_name, frame in {
            "train": train_metadata,
            "validation": valid_df,
            "test": test_df,
        }.items():
            missing = REQUIRED_METADATA - set(frame.columns)
            assert not missing, f"{split_name} missing columns: {sorted(missing)}"
            assert not frame.empty
            assert frame["audio_path"].is_unique
            assert set(frame["sample_rate"].astype(int)) == {16_000}
            missing_files = [
                value for value in frame["audio_path"]
                if not (DATASET_ROOT / value).is_file()
            ]
            assert not missing_files, f"{split_name} missing audio: {missing_files[:3]}"

        for split_name, trials in {
            "validation": valid_trials,
            "test": test_trials,
        }.items():
            missing = REQUIRED_TRIALS - set(trials.columns)
            assert not missing, f"{split_name} trials missing: {sorted(missing)}"
            assert set(trials["label"].astype(int)) == {0, 1}

        speaker_sets = {
            "train": set(train_metadata[LABEL_COL].astype(str)),
            "validation": set(valid_df[LABEL_COL].astype(str)),
            "test": set(test_df[LABEL_COL].astype(str)),
        }
        assert speaker_sets["train"].isdisjoint(speaker_sets["validation"])
        assert speaker_sets["train"].isdisjoint(speaker_sets["test"])
        assert speaker_sets["validation"].isdisjoint(speaker_sets["test"])

        assert set(train_df["role"]) == {"TRAIN"}
        assert set(valid_df["role"]) == {"ENROLLMENT", "QUERY"}
        assert set(test_df["role"]) == {"ENROLLMENT", "QUERY"}
        assert set(closed_train_protocol["speaker_id"]) == set(closed_valid_protocol["speaker_id"])
        assert set(closed_train_protocol["speaker_id"]) == set(closed_test_protocol["speaker_id"])
        closed_path_sets = [
            set(frame["audio_path"])
            for frame in (closed_train_protocol, closed_valid_protocol, closed_test_protocol)
        ]
        assert all(
            left.isdisjoint(right)
            for index, left in enumerate(closed_path_sets)
            for right in closed_path_sets[index + 1:]
        )
        for gallery, queries in (
            (open_valid_gallery, open_valid_queries),
            (open_test_gallery, open_test_queries),
        ):
            gallery_speakers = set(gallery["speaker_id"].astype(str))
            assert all(
                (speaker in gallery_speakers) == bool(is_known)
                for speaker, is_known in zip(
                    queries["query_speaker_id"].astype(str),
                    queries["is_known"].astype(int),
                )
            )

        display(pd.DataFrame([
            {
                "split": name,
                "audio": len(frame),
                "speakers": frame[LABEL_COL].nunique(),
            }
            for name, frame in {
                "train": train_metadata,
                "validation": valid_df,
                "test": test_df,
            }.items()
        ]))
        print("Dataset protocol checks passed")
        """
    ),
    markdown("## 4. Audio pipeline"),
    code(
        """
        def load_segment(path, training):
            info = sf.info(path)
            source_frames = round(
                SEGMENT_SAMPLES * info.samplerate / TARGET_SAMPLE_RATE
            )
            max_start = max(0, info.frames - source_frames)
            start = (
                torch.randint(0, max_start + 1, (1,)).item()
                if training and max_start
                else max_start // 2
            )
            audio, sample_rate = sf.read(
                path,
                start=start,
                frames=source_frames,
                dtype="float32",
                always_2d=True,
            )
            waveform = torch.from_numpy(audio.mean(axis=1)).float()
            if sample_rate != TARGET_SAMPLE_RATE:
                waveform = torchaudio.functional.resample(
                    waveform, sample_rate, TARGET_SAMPLE_RATE
                )
            if waveform.numel() == 0 or not torch.isfinite(waveform).all():
                raise ValueError(f"Invalid audio: {path}")
            valid_samples = min(waveform.numel(), SEGMENT_SAMPLES)
            waveform = waveform[:SEGMENT_SAMPLES]
            if waveform.numel() < SEGMENT_SAMPLES:
                waveform = F.pad(
                    waveform, (0, SEGMENT_SAMPLES - waveform.numel())
                )
            return waveform, valid_samples


        class VoxVietnamAudioDataset(Dataset):
            def __init__(self, frame, training=False):
                self.frame = frame.reset_index(drop=True)
                self.training = training

            def __len__(self):
                return len(self.frame)

            def __getitem__(self, index):
                row = self.frame.iloc[index]
                relative_path = str(row["audio_path"])
                waveform, valid_samples = load_segment(
                    DATASET_ROOT / relative_path, self.training
                )
                return (
                    waveform,
                    valid_samples,
                    relative_path,
                    str(row[LABEL_COL]),
                )


        def collate_audio(batch):
            waveforms, valid_samples, paths, speakers = zip(*batch)
            waveforms = torch.stack(waveforms)
            lengths = torch.tensor(valid_samples, dtype=torch.float32)
            lengths = lengths / waveforms.shape[1]
            return waveforms, lengths, list(paths), list(speakers)
        """
    ),
    markdown("## 5. Checkpoint-selection verification metrics"),
    code(
        """
        def verification_curve(labels, scores, p_target=0.01):
            labels = np.asarray(labels, dtype=np.int64)
            scores = np.asarray(scores, dtype=np.float64)
            assert labels.shape == scores.shape
            assert set(np.unique(labels)) == {0, 1}
            assert np.isfinite(scores).all()

            fpr, tpr, thresholds = roc_curve(
                labels, scores, pos_label=1, drop_intermediate=False
            )
            fnr = 1.0 - tpr
            eer_index = int(np.argmin(np.abs(fpr - fnr)))
            eer = float((fpr[eer_index] + fnr[eer_index]) / 2.0)

            dcf = p_target * fnr + (1.0 - p_target) * fpr
            normalizer = min(p_target, 1.0 - p_target)
            min_dcf_index = int(np.argmin(dcf))

            far_mask = fpr <= 0.01
            tar_at_far_1pct = float(tpr[far_mask].max()) if far_mask.any() else 0.0
            return {
                "eer": eer,
                "eer_threshold": float(thresholds[eer_index]),
                "min_dcf": float(dcf[min_dcf_index] / normalizer),
                "min_dcf_threshold": float(thresholds[min_dcf_index]),
                "tar_at_far_1pct": tar_at_far_1pct,
            }


        def rates_at_threshold(labels, scores, threshold):
            labels = np.asarray(labels, dtype=np.int64)
            predictions = np.asarray(scores) >= threshold
            positives = labels == 1
            negatives = ~positives
            far = float(predictions[negatives].mean())
            frr = float((~predictions[positives]).mean())
            return {
                "threshold": float(threshold),
                "far": far,
                "frr": frr,
                "tar": float(1.0 - frr),
            }


        def score_trials(frame, embeddings, trials):
            assert len(frame) == len(embeddings)
            path_to_embedding = {
                str(path): embedding
                for path, embedding in zip(frame["audio_path"], embeddings)
            }
            enrollment = frame[frame["role"] == "ENROLLMENT"]
            centroids = {}
            for speaker, group in enrollment.groupby(LABEL_COL):
                vectors = np.stack([
                    path_to_embedding[str(path)] for path in group["audio_path"]
                ])
                centroid = vectors.mean(axis=0)
                centroids[str(speaker)] = centroid / np.linalg.norm(centroid)

            scores = []
            for row in trials.itertuples(index=False):
                centroid = centroids[str(row.enrollment_speaker_id)]
                query = path_to_embedding[str(row.query_audio_path)]
                scores.append(float(np.dot(centroid, query)))
            return np.asarray(scores, dtype=np.float64)
        """
    ),
    markdown(
        "## 6. Standalone three-task evaluator\n\n"
        "This generated cell embeds the tested `src/speaker/evaluation.py` "
        "snapshot. Kaggle needs only this notebook and the processed dataset."
    ),
    code(embedded_evaluation()),
    code(embedded_checkpointing()),
    code(
        """
        # Protocol helper must exist before frozen validation and training cells.
        def protocol_vectors(cache, protocol, path_column="audio_path"):
            paths = protocol[path_column].astype(str)
            missing = sorted(set(paths) - set(cache))
            assert not missing, f"Missing cached protocol embeddings: {missing[:3]}"
            return np.stack([cache[str(path)] for path in paths])
        """
    ),
    markdown("## 7. Frozen ECAPA baseline"),
    code(
        """
        print("Device:", DEVICE)
        print("Batch size:", BATCH_SIZE)
        print("Gradient accumulation:", GRAD_ACCUM)

        pretrained = EncoderClassifier.from_hparams(
            source="speechbrain/spkrec-ecapa-voxceleb",
            savedir="/kaggle/working/pretrained_ecapa",
            run_opts={"device": str(DEVICE)},
            freeze_params=True,
        )
        pretrained.eval()
        """
    ),
    code(
        """
        def evaluation_loader(frame):
            return DataLoader(
                VoxVietnamAudioDataset(frame, training=False),
                batch_size=BATCH_SIZE,
                shuffle=False,
                num_workers=NUM_WORKERS,
                pin_memory=USE_AMP,
                collate_fn=collate_audio,
            )


        @torch.inference_mode()
        def extract_pretrained_embeddings(
            frame, description, encoder_classifier=pretrained
        ):
            features = []
            for waveforms, lengths, _, _ in tqdm(
                evaluation_loader(frame), desc=description, leave=False
            ):
                embeddings = encoder_classifier.encode_batch(
                    waveforms.to(DEVICE, non_blocking=True),
                    wav_lens=lengths.to(DEVICE, non_blocking=True),
                    normalize=False,
                ).squeeze(1)
                embeddings = F.normalize(embeddings.float(), p=2, dim=-1)
                features.append(embeddings.cpu().numpy())
            result = np.concatenate(features)
            assert result.shape == (len(frame), 192)
            assert np.isfinite(result).all()
            return result


        print("Frozen ECAPA initialized")
        """
    ),
    markdown("## 8. Execute frozen ECAPA evaluation"),
    code(
        """
        frozen_embedding_matrix = extract_pretrained_embeddings(
            evaluation_df, "Frozen ECAPA: cache every unique audio", pretrained
        )
        assert evaluation_df["audio_path"].is_unique
        frozen_embedding_cache = dict(zip(
            evaluation_df["audio_path"].astype(str), frozen_embedding_matrix
        ))
        assert len(frozen_embedding_cache) == len(evaluation_df)

        frozen_closed_validation = evaluate_closed_validation(
            protocol_vectors(frozen_embedding_cache, closed_train_protocol), closed_train_protocol["speaker_id"],
            protocol_vectors(frozen_embedding_cache, closed_valid_protocol), closed_valid_protocol["speaker_id"],
        )
        frozen_validation_metrics = frozen_closed_validation["metrics"]
        frozen_summary = pd.DataFrame([{
            "model": "frozen ECAPA-TDNN",
            "validation_closed_macro_f1": frozen_validation_metrics["macro_f1"],
            "validation_closed_accuracy": frozen_validation_metrics["accuracy"],
        }])
        display(frozen_summary)
        """
    ),
    markdown("## 9. Fine-tuning model, classifier, and DataLoader"),
    code(
        """
        train_speakers = sorted(train_df[LABEL_COL].astype(str).unique())
        speaker_to_id = {
            speaker: index for index, speaker in enumerate(train_speakers)
        }
        NUM_SPEAKERS = len(speaker_to_id)


        def collate_train(batch):
            waveforms, valid_samples, _, speakers = zip(*batch)
            waveforms = torch.stack(waveforms)
            lengths = torch.tensor(valid_samples, dtype=torch.float32)
            lengths = lengths / waveforms.shape[1]
            labels = torch.tensor(
                [speaker_to_id[speaker] for speaker in speakers], dtype=torch.long
            )
            return waveforms, lengths, labels


        train_dataset = VoxVietnamAudioDataset(train_df, training=True)
        loader_generator = torch.Generator().manual_seed(SEED)
        train_loader = DataLoader(
            train_dataset,
            batch_size=BATCH_SIZE,
            shuffle=True,
            generator=loader_generator,
            drop_last=True,
            num_workers=NUM_WORKERS,
            pin_memory=USE_AMP,
            collate_fn=collate_train,
        )

        print("Train audio:", len(train_dataset))
        print("Train speakers:", NUM_SPEAKERS)
        print("Train batches:", len(train_loader))
        """
    ),
    code(
        """
        class ECAPAFineTuner(nn.Module):
            def __init__(self, pretrained_model, num_speakers):
                super().__init__()
                self.compute_features = pretrained_model.mods.compute_features
                self.feature_normalizer = pretrained_model.mods.mean_var_norm
                self.encoder = pretrained_model.mods.embedding_model
                self.classifier = Classifier(
                    input_size=192, out_neurons=num_speakers
                )

            def forward(self, waveforms, lengths):
                features = self.compute_features(waveforms)
                features = self.feature_normalizer(features, lengths)
                embeddings = self.encoder(features, lengths)
                scores = self.classifier(embeddings)
                return scores, embeddings


        model = ECAPAFineTuner(pretrained, NUM_SPEAKERS).to(DEVICE)
        pretrained.mods.classifier.to("cpu")
        if "mean_var_norm_emb" in pretrained.mods:
            pretrained.mods.mean_var_norm_emb.to("cpu")

        criterion = LogSoftmaxWrapper(
            AdditiveAngularMargin(margin=0.2, scale=30)
        ).to(DEVICE)

        for parameter in model.encoder.parameters():
            parameter.requires_grad_(False)

        optimizer = torch.optim.AdamW(
            [
                {"params": model.encoder.parameters(), "lr": ENCODER_LEARNING_RATE},
                {"params": model.classifier.parameters(), "lr": CLASSIFIER_LEARNING_RATE},
            ],
            weight_decay=WEIGHT_DECAY,
        )
        scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
            optimizer, mode="min", factor=0.5, patience=1
        )
        scaler = torch.amp.GradScaler("cuda", enabled=USE_AMP)
        """
    ),
    markdown("## 10. Training and validation functions"),
    code(
        """
        def autocast_context():
            if USE_AMP:
                return torch.autocast(device_type="cuda", dtype=torch.float16)
            return nullcontext()


        def train_one_epoch(epoch, warmup_epochs):
            model.train()
            if epoch < warmup_epochs:
                model.encoder.eval()
            optimizer.zero_grad(set_to_none=True)
            losses, predictions, targets = [], [], []

            progress = tqdm(train_loader, desc=f"Train {epoch + 1}", leave=False)
            for step, (waveforms, lengths, labels) in enumerate(progress):
                waveforms = waveforms.to(DEVICE, non_blocking=True)
                lengths = lengths.to(DEVICE, non_blocking=True)
                labels = labels.to(DEVICE, non_blocking=True)

                with autocast_context():
                    scores, _ = model(waveforms, lengths)
                    loss = criterion(scores, labels.unsqueeze(1))

                scaler.scale(loss / GRAD_ACCUM).backward()
                update = (step + 1) % GRAD_ACCUM == 0 or step + 1 == len(train_loader)
                if update:
                    scaler.unscale_(optimizer)
                    torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=5.0)
                    scaler.step(optimizer)
                    scaler.update()
                    optimizer.zero_grad(set_to_none=True)

                predictions.extend(scores.squeeze(1).argmax(-1).detach().cpu().tolist())
                targets.extend(labels.detach().cpu().tolist())
                losses.append(float(loss.detach().cpu()))
                progress.set_postfix(loss=f"{np.mean(losses):.4f}")

            return {
                "train_loss": float(np.mean(losses)),
                "train_macro_f1": float(f1_score(
                    targets, predictions, average="macro", zero_division=0
                )),
            }


        @torch.inference_mode()
        def extract_finetuned_embeddings(frame, description):
            model.eval()
            features = []
            for waveforms, lengths, _, _ in tqdm(
                evaluation_loader(frame), desc=description, leave=False
            ):
                waveforms = waveforms.to(DEVICE, non_blocking=True)
                lengths = lengths.to(DEVICE, non_blocking=True)
                with autocast_context():
                    _, embeddings = model(waveforms, lengths)
                embeddings = F.normalize(
                    embeddings.squeeze(1).float(), p=2, dim=-1
                )
                features.append(embeddings.cpu().numpy())
            result = np.concatenate(features)
            assert result.shape == (len(frame), 192)
            assert np.isfinite(result).all()
            return result


        def validate_verification(epoch):
            embeddings = extract_finetuned_embeddings(
                valid_df, f"Validation {epoch + 1}"
            )
            scores = score_trials(valid_df, embeddings, valid_trials)
            return verification_curve(valid_trials["label"], scores)
        """
    ),
    markdown("## 11. Pre-training memory probes"),
    code(
        """
        process = psutil.Process(os.getpid())


        def memory_snapshot(label):
            message = f"{label}: RAM={process.memory_info().rss / 1024**3:.2f} GiB"
            if USE_AMP:
                message += (
                    f", GPU allocated={torch.cuda.memory_allocated() / 1024**3:.2f} GiB"
                    f", reserved={torch.cuda.memory_reserved() / 1024**3:.2f} GiB"
                )
            print(message)


        memory_snapshot("Before probes")
        for debug_step, debug_batch in enumerate(train_loader):
            if debug_step >= 20:
                break
        print("DataLoader probe passed")

        model.train()
        model.encoder.eval()
        optimizer.zero_grad(set_to_none=True)
        for debug_step, (waveforms, lengths, labels) in enumerate(train_loader):
            waveforms = waveforms.to(DEVICE)
            lengths = lengths.to(DEVICE)
            labels = labels.to(DEVICE)
            with autocast_context():
                scores, embeddings = model(waveforms, lengths)
                debug_loss = criterion(scores, labels.unsqueeze(1))
            scaler.scale(debug_loss).backward()
            optimizer.zero_grad(set_to_none=True)
            assert scores.shape == (len(labels), 1, NUM_SPEAKERS)
            assert embeddings.shape == (len(labels), 1, 192)
            assert torch.isfinite(debug_loss)
            if debug_step >= 5:
                break

        del waveforms, lengths, labels, scores, embeddings, debug_loss, debug_batch
        gc.collect()
        if USE_AMP:
            torch.cuda.empty_cache()
        memory_snapshot("After probes")
        print("Forward/backward probe passed")
        """
    ),
    markdown("## 12. Execute fine-tuning; select checkpoint on validation EER/minDCF"),
    code(
        """
        training_config = {
            "dataset": EXPECTED_DATASET,
            "dataset_root": str(DATASET_ROOT),
            "device": str(DEVICE),
            "batch_size": BATCH_SIZE,
            "gradient_accumulation": GRAD_ACCUM,
            "effective_batch": BATCH_SIZE * GRAD_ACCUM,
            "segment_seconds": SEGMENT_SECONDS,
            "train_audio": len(train_df),
            "train_speakers": NUM_SPEAKERS,
            "validation_audio": len(valid_df),
            "validation_trials": len(valid_trials),
            "test_audio": len(test_df),
            "test_trials": len(test_trials),
            "selection_metric": "validation-only closed F1, verification EER, open AUROC, balanced score",
            "max_epochs": MAX_EPOCHS,
            "warmup_epochs": WARMUP_EPOCHS,
            "early_stopping_patience": EARLY_STOPPING_PATIENCE,
            "encoder_learning_rate": ENCODER_LEARNING_RATE,
            "classifier_learning_rate": CLASSIFIER_LEARNING_RATE,
            "weight_decay": WEIGHT_DECAY,
            "checkpoint_dir": str(CHECKPOINT_DIR),
            "checkpoint_eval_interval": CHECKPOINT_EVAL_INTERVAL,
            "max_rolling_checkpoints": MAX_ROLLING_CHECKPOINTS,
            "max_closed_f1_drop": MAX_CLOSED_F1_DROP,
        }
        TRAINING_CONFIG_PATH.write_text(
            json.dumps(training_config, indent=2) + "\\n", encoding="utf-8"
        )
        print(json.dumps(training_config, indent=2))
        """
    ),
    code(
        """
        checkpoint_manager = CheckpointManager(CHECKPOINT_DIR, MAX_ROLLING_CHECKPOINTS)
        bad_epochs = 0
        history = []

        for epoch in range(MAX_EPOCHS):
            if epoch == WARMUP_EPOCHS:
                for parameter in model.encoder.parameters():
                    parameter.requires_grad_(True)
                print("ECAPA encoder unfrozen")

            row = {"epoch": epoch + 1}
            row.update(train_one_epoch(epoch, WARMUP_EPOCHS))
            validation = validate_verification(epoch)
            row.update({f"valid_{key}": value for key, value in validation.items()})
            validation_cache = extract_finetuned_embeddings(
                evaluation_df, f"Validation checkpoint epoch {epoch + 1}"
            )
            validation_vectors = dict(zip(evaluation_df["audio_path"].astype(str), validation_cache))
            closed_validation = evaluate_closed_validation(
                protocol_vectors(validation_vectors, closed_train_protocol), closed_train_protocol["speaker_id"],
                protocol_vectors(validation_vectors, closed_valid_protocol), closed_valid_protocol["speaker_id"],
            )["metrics"]
            verification_validation = evaluate_verification_validation(
                validation_vectors, valid_enrollment_protocol, valid_trials
            )["metrics"]
            open_validation = evaluate_open_validation(
                validation_vectors, open_valid_gallery, open_valid_queries
            )["metrics"]
            row.update({f"valid_closed_{key}": value for key, value in closed_validation.items()})
            row.update({f"valid_open_{key}": value for key, value in open_validation.items()})
            history.append(row)
            print(row)

            scheduler.step(validation["eer"])
            compact_payload = checkpoint_payload(
                model.encoder.state_dict(), epoch + 1, "latest",
                {"verification": verification_validation, "closed": closed_validation, "open": open_validation},
                training_config, model.classifier.state_dict(),
            )
            checkpoint_manager.record_latest(compact_payload, epoch + 1)
            checkpoint_manager.save_if_improved("closed", checkpoint_payload(model.encoder.state_dict(), epoch + 1, "closed", closed_validation, training_config, model.classifier.state_dict()), closed_validation, epoch + 1)
            checkpoint_manager.save_if_improved("verification", checkpoint_payload(model.encoder.state_dict(), epoch + 1, "verification", verification_validation, training_config, model.classifier.state_dict()), verification_validation, epoch + 1)
            checkpoint_manager.save_if_improved("open", checkpoint_payload(model.encoder.state_dict(), epoch + 1, "open", open_validation, training_config, model.classifier.state_dict()), open_validation, epoch + 1)
            balanced_metrics = {"closed_macro_f1": closed_validation["macro_f1"], "verification_eer": verification_validation["eer"], "open_auroc": open_validation["known_unknown_auroc"]}
            balanced_rank = rank_metrics("balanced", balanced_metrics, epoch + 1, frozen_closed_macro_f1=frozen_validation_metrics["macro_f1"], max_closed_f1_drop=MAX_CLOSED_F1_DROP)
            if balanced_rank is not None:
                checkpoint_manager.save_if_improved("balanced", checkpoint_payload(model.encoder.state_dict(), epoch + 1, "balanced", balanced_metrics, training_config, model.classifier.state_dict()), balanced_metrics, epoch + 1, frozen_closed_macro_f1=frozen_validation_metrics["macro_f1"], max_closed_f1_drop=MAX_CLOSED_F1_DROP)
            if balanced_rank is not None:
                bad_epochs = 0
            else:
                bad_epochs += 1

            pd.DataFrame(history).to_csv(TRAINING_HISTORY_PATH, index=False)
            pd.DataFrame(history).to_csv(CHECKPOINT_DIR / "checkpoint_validation_history.csv", index=False)
            memory_snapshot(f"End epoch {epoch + 1}")
            if bad_epochs >= EARLY_STOPPING_PATIENCE:
                print("Early stopping")
                break
        """
    ),
    markdown("## 13. Restore checkpoint and cache fine-tuned embeddings"),
    code(
        """
        selected_balanced_path = BEST_BALANCED_PATH
        if not selected_balanced_path.is_file():
            print("No balanced epoch satisfied closed-F1 constraint; falling back to best closed checkpoint")
            selected_balanced_path = BEST_CLOSED_PATH
        CHECKPOINT = selected_balanced_path
        assert CHECKPOINT.is_file(), f"Checkpoint not found: {CHECKPOINT}"
        checkpoint = torch.load(CHECKPOINT, map_location="cpu", weights_only=False)
        model.encoder.load_state_dict(checkpoint["encoder"])
        model.classifier.load_state_dict(checkpoint["classifier"])
        model.to(DEVICE).eval()

        finetuned_embedding_matrix = extract_finetuned_embeddings(
            evaluation_df, "Fine-tuned ECAPA: cache every unique audio"
        )
        assert evaluation_df["audio_path"].is_unique
        finetuned_embedding_cache = dict(zip(
            evaluation_df["audio_path"].astype(str), finetuned_embedding_matrix
        ))
        assert len(finetuned_embedding_cache) == len(evaluation_df)
        print(f"Cached {len(evaluation_df)} fine-tuned audio embeddings")
        """
    ),
    markdown("## 14. Execute fine-tuned ECAPA evaluation and comparison"),
    code(
        """
        def protocol_vectors(cache, protocol, path_column="audio_path"):
            missing = sorted(set(protocol[path_column].astype(str)) - set(cache))
            assert not missing, f"Missing cached protocol embeddings: {missing[:3]}"
            return np.stack([cache[str(path)] for path in protocol[path_column]])


        def evaluate_three_tasks(model_name, cache, save_artifacts=False):
            # Closed set: select LinearSVC using validation only, then test once.
            closed_selection = select_closed_set_svm(
                protocol_vectors(cache, closed_train_protocol),
                closed_train_protocol["speaker_id"],
                protocol_vectors(cache, closed_valid_protocol),
                closed_valid_protocol["speaker_id"],
            )
            closed_test_result = evaluate_closed_set(
                closed_selection["model"],
                protocol_vectors(cache, closed_test_protocol),
                closed_test_protocol["speaker_id"],
            )
            closed_metrics = {
                "model": model_name,
                "selected_c": closed_selection["selected_c"],
                "class_weight": closed_selection["class_weight"],
                "validation": closed_selection["validation"],
                "test": closed_test_result["metrics"],
                "test_per_speaker_recall": closed_test_result["per_speaker_recall"],
            }

            # Verification: select minDCF threshold on validation, reuse unchanged.
            valid_centroids = build_centroids(
                protocol_vectors(cache, valid_enrollment_protocol),
                valid_enrollment_protocol["speaker_id"],
            )
            valid_verification_scores = score_cosine_trials(
                cache, valid_centroids, valid_trials.to_dict("records")
            )
            valid_verification = verification_metrics(
                valid_trials["label"], valid_verification_scores
            )
            verification_threshold = valid_verification["min_dcf_threshold"]
            test_centroids = build_centroids(
                protocol_vectors(cache, test_enrollment_protocol),
                test_enrollment_protocol["speaker_id"],
            )
            test_verification_scores = score_cosine_trials(
                cache, test_centroids, test_trials.to_dict("records")
            )
            test_verification = verification_metrics(
                test_trials["label"], test_verification_scores
            )
            test_verification.update(rates_at_threshold(
                test_trials["label"], test_verification_scores,
                verification_threshold,
            ))
            verification_result = {
                "model": model_name,
                "validation": valid_verification,
                "test": test_verification,
            }

            # Open set: validation gallery/queries select rejection threshold.
            valid_gallery_centroids = build_centroids(
                protocol_vectors(cache, open_valid_gallery),
                open_valid_gallery["speaker_id"],
            )
            open_valid_candidates, open_valid_scores = predict_open_set(
                protocol_vectors(cache, open_valid_queries, "query_audio_path"),
                valid_gallery_centroids,
                threshold=-1.0,
            )
            open_set_threshold = select_open_set_threshold(
                open_valid_queries["is_known"], open_valid_scores
            )
            open_valid_result = open_set_metrics(
                open_valid_queries["query_speaker_id"],
                open_valid_queries["is_known"],
                open_valid_candidates,
                open_valid_scores,
                threshold=open_set_threshold,
            )
            test_gallery_centroids = build_centroids(
                protocol_vectors(cache, open_test_gallery),
                open_test_gallery["speaker_id"],
            )
            open_test_candidates, open_test_scores = predict_open_set(
                protocol_vectors(cache, open_test_queries, "query_audio_path"),
                test_gallery_centroids,
                threshold=-1.0,
            )
            open_test_result = open_set_metrics(
                open_test_queries["query_speaker_id"],
                open_test_queries["is_known"],
                open_test_candidates,
                open_test_scores,
                threshold=open_set_threshold,
            )
            open_result = {
                "model": model_name,
                "validation": open_valid_result,
                "test": open_test_result,
            }

            if save_artifacts:
                write_metrics_json("/kaggle/working/verification_metrics.json", verification_result)
                verification_output = test_trials.copy()
                verification_output["score"] = test_verification_scores
                verification_output["accepted"] = test_verification_scores >= verification_threshold
                verification_output.to_csv("/kaggle/working/verification_trial_scores.csv", index=False)

                write_metrics_json("/kaggle/working/closed_set_metrics.json", closed_metrics)
                closed_output = closed_test_protocol.copy()
                closed_output["predicted_speaker_id"] = closed_test_result["predictions"]
                closed_output.to_csv("/kaggle/working/closed_set_predictions.csv", index=False)
                pd.DataFrame(
                    closed_test_result["confusion_matrix"],
                    index=closed_test_result["classes"],
                    columns=closed_test_result["classes"],
                ).to_csv("/kaggle/working/closed_set_confusion_matrix.csv")

                write_metrics_json("/kaggle/working/open_set_metrics.json", open_result)
                open_output = open_test_queries.copy()
                open_output["predicted_speaker_id"] = np.where(
                    open_test_scores >= open_set_threshold,
                    open_test_candidates,
                    UNKNOWN_SPEAKER,
                )
                open_output["max_score"] = open_test_scores
                open_output["threshold"] = open_set_threshold
                open_output.to_csv("/kaggle/working/open_set_predictions.csv", index=False)

            return {
                "model": model_name,
                "closed_set": closed_metrics,
                "verification": verification_result,
                "open_set": open_result,
            }


        frozen_results = evaluate_three_tasks(
            "frozen ECAPA-TDNN", frozen_embedding_cache, save_artifacts=False
        )
        finetuned_results = evaluate_three_tasks(
            "fine-tuned ECAPA-TDNN", finetuned_embedding_cache, save_artifacts=True
        )

        three_task_summary = pd.DataFrame([
            {
                "model": result["model"],
                "closed_set_test_accuracy": result["closed_set"]["test"]["accuracy"],
                "closed_set_test_macro_f1": result["closed_set"]["test"]["macro_f1"],
                "verification_test_eer": result["verification"]["test"]["eer"],
                "verification_test_min_dcf": result["verification"]["test"]["min_dcf"],
                "open_set_test_known_id_accuracy": result["open_set"]["test"]["known_identification_accuracy"],
                "open_set_test_unknown_rejection": result["open_set"]["test"]["unknown_rejection_rate"],
                "open_set_test_auroc": result["open_set"]["test"]["known_unknown_auroc"],
            }
            for result in (frozen_results, finetuned_results)
        ])
        three_task_summary.to_csv("/kaggle/working/three_task_summary.csv", index=False)
        display(three_task_summary)
        """
    ),
    markdown(
        """
        ## Output artifacts

        - `ecapa_voxvietnam_best.pt`
        - `ecapa_training_config.json`
        - `ecapa_training_history.csv`
        - `evaluation/frozen/{verification,closed_set,open_set}_metrics.json`
        - `evaluation/finetuned/{verification,closed_set,open_set}_metrics.json`
        - Model-specific trial scores, predictions, and confusion matrix under
          each evaluation directory.
        - `three_task_summary.csv`

        These paths are an artifact contract, not claimed results. Populate them
        only by running this notebook on gated VoxVietnam audio with a Kaggle GPU.
        Never tune a checkpoint, SVM hyperparameter, or threshold on test scores.
        """
    ),
]


# Keep orchestration in src/speaker/evaluation.py. Replace the legacy inline
# cell while preserving deterministic notebook generation from this script.
for cell in CELLS:
    source = cell.get("source", "")
    if cell.get("cell_type") == "code" and source.startswith("def protocol_vectors("):
        cell["source"] = dedent(
            """
            frozen_results = evaluate_three_tasks(
                "frozen ECAPA-TDNN",
                frozen_embedding_cache,
                THREE_TASK_PROTOCOLS,
                output_dir=FROZEN_EVALUATION_DIR,
            )
            finetuned_results = evaluate_three_tasks(
                "fine-tuned ECAPA-TDNN",
                finetuned_embedding_cache,
                THREE_TASK_PROTOCOLS,
                output_dir=FINETUNED_EVALUATION_DIR,
            )
            finetuned_summary = pd.DataFrame(
                summarize_three_task_results([finetuned_results])
            )
            display(finetuned_summary)

            three_task_summary = pd.DataFrame(
                summarize_three_task_results([frozen_results, finetuned_results])
            )
            three_task_summary.to_csv(SUMMARY_PATH, index=False)
            display(three_task_summary)
            """
        ).strip() + "\n"


def main() -> None:
    notebook = {
        "cells": CELLS,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {
                "name": "python",
                "version": "3.11",
            },
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }
    OUTPUT.write_text(
        json.dumps(notebook, ensure_ascii=False, indent=1) + "\n",
        encoding="utf-8",
    )
    print(f"Wrote {OUTPUT} with {len(CELLS)} cells")


if __name__ == "__main__":
    main()
